// <auto-generated />
namespace AttendanceBot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Configuration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Configuration));
        
        string IMigrationMetadata.Id
        {
            get { return "201811260539379_Configuration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
